### ISSUE TITLE
Bug when execute Make command

### ISSUE THREAD

**Issue by bouharb** [korfuri/client_cpp#20]
Hello,

google/protobuf/port_def.inc no such file or directory

I use libprotoc 3.7.1

Can you detail builiding project with cmake ?

Thank you in advance

**Comment by korfuri** [comment]
Hey, I have not updated this project in years, so it's entirely possible that the dependency on libprotoc won't work with a recent version of the lib. I unfortunately don't have the time nor the interest in debugging this.

If you want an actively maintained client library for Prometheus, I think https://github.com/jupp0r/prometheus-cpp is a safer bet.
